config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ru/ do
    root "main#index"

    get 'decks', to: "decks#decks"
    get 'show_deck', to: "decks#show"
    get 'edit_deck', to: "decks#edit"
    post 'copy_deck', to: "decks#copy"
    delete 'delete_deck', to: "decks#delete"

    get 'logout', to: "session#logout"
    get 'login', to: "session#login"
    get 'signup', to: "users#new"

    post 'authorize', to: "session#authorize"

    get 'filtered', to: "main#filtered"
    get 'deck_format', to: "main#deck_format", format: 'turbo_stream'
    patch 'toggle_filters', to: "main#toggle_filters"

    post 'create_deck', to: "deck_editor#create_deck"
    patch 'save_deck', to: "deck_editor#save_deck"
    delete 'delete_current_deck', to: "deck_editor#delete_deck"

    patch 'add_card', to: "deck_editor#add_card"
    patch 'remove_card', to: "deck_editor#remove_card"

    resources :users
  end
end

app/controllers/main_controller.rb
# frozen_string_literal: true

# main controller
class MainController < ApplicationController
  before_action :init_deck, :show_filters_init

  before_action :init_meta_info, only: %i[index filtered]
  before_action :init_params, only: [:filtered]
  before_action :base_params, only: [:index]
  before_action :redirect_if_not_logged_in, only: [:deck_format]

  layout 'clear'

  def index
    @page = page(CardInstance)
    @cards = CardInstance.filtered(@params).page @page
  end

  def filtered
    @page = page(CardInstance)
    @cards = CardInstance.filtered(@params).page @page
    render 'index'
  end

  def toggle_filters
    session[:show_filters] = !@show_filters
    head :ok
  end

  def deck_format; end

  private

  def init_meta_info
    @expansions = [''] + Expansion.all
    @supertypes = [''] + CardType.where(type_scope: :super).to_a
    @types = [''] + CardType.where(type_scope: :normal).to_a
    @subtypes = [''] + CardType.where(type_scope: :sub).to_a
  end

  def show_filters_init
    @show_filters = session[:show_filters]
  end

  def init_params
    @params = params
  end

  def base_params
    @params = { color_w: 1, color_b: 1, color_u: 1, color_r: 1, color_g: 1, color_c: 1 }
  end
end

app/helpers/main_helper.rb
module MainHelper
  def user_is_deckbuilding
    return false if session[:is_deckbuilding].blank?
    session[:is_deckbuilding]
  end
end

app/views/main/_card_extended.html.erb
<div id="<%= dom_id card_instance %>" class="row my-2 align-items-center">
  <div class="col-3 me-2">
    <% if card_instance.image.representable? %>
      <%= image_tag card_instance.image.representation(resize_to_limit: [284, 400]) %>
    <% else %>
      <%= link_to rails_blob_path(card_instance.image) %>
    <% end %>
  </div>

  <div class="col-4">
    <div class="">
      <%= process_text(card_instance.card.text) %>
    </div>
    <div class="italic mt-2"><%= card_instance.flavour_text %></div>
  </div>
</div>

app/views/main/_card_header.html.erb
<div class="row align-items-center">
  <div class="col-11 row list-group list-group-horizontal p-0 outline position-sticky">
    <div class="col-3 list-group-item centered py-1">
      <span><%= t('name') %></span>
    </div>
    <div class="col-4 list-group-item centered py-0">
      <span><%= t('type') %></span>
    </div>
    <div class="col-2 list-group-item centered py-0">
      <span><%= t('cost') %></span>
    </div>
    <div class="col-1 list-group-item centered py-0">
      <span><%= t('p/t') %></span>
    </div>
    <div class="col-1 list-group-item centered py-0">
      <span><%= t('expansion') %></span>
    </div>
    <div class="col-1 list-group-item centered py-0">
      <span><%= t('rarity') %></span>
    </div>
  </div>
  <div class="col-1 ms-4">
    <div class="d-flex">
      <button id="collapse-btn" class="btn btn-secondary me-2"><%= t('collapse') %></button>
      <button id="expand-btn" class="btn btn-secondary"><%= t('expand') %></button>
    </div>
  </div>
</div>

app/views/main/_cards.html.erb
<div class="col-7 mb-5 me-0 ps-5">
  <% if cards.present? %>
    <div class="cards-heading mb-5 w-100">
      <%= render partial: "card_header" %>
    </div>

    <div class="mt-5 card-entries w-100">
      <% cards.each do |card| %>
        <%= render card %>
      <% end %>
    </div>
  <% else %>
    <div class="h4 mt-5">
      <%= t('no-cards') %>
    </div>
  <% end %>
</div>

app/views/main/_menu.html.erb
<div class="row justify-content-center">
  <%= link_to t('filters'), toggle_filters_path, class: "btn btn-outline-primary text-dark col-6", id: 'filter-btn', data: { "turbo-method": :patch } %>
</div>

<%= form_with url: filtered_path, method: :get, class: "mt-3 #{'d-none' unless @show_filters}", id: 'filter-form' do |form| %>
  <div class="row form-group">
    <%= form.label :name, t('name'), class: "col-3"%>
    <div class="col-9">
      <%= form.text_field :name, class: "form-control", value: @params[:name] %>
    </div>
  </div>
  <div class="row mt-2 form-group">
    <%= form.label :rules, t('rules'), class: "col-3"%>
    <div class="col-9">
      <%= form.text_field :rules, class: "form-control", value: @params[:rules] %>
    </div>
  </div>
  <div class="row mt-2 form-group">
    <%= form.label :flavour, t('flavour'), class: "col-3"%>
    <div class="col-9">
      <%= form.text_field :flavour, class: "form-control", value: @params[:flavour] %>
    </div>
  </div>

  <div class="ms-2 gx-4 row mt-2 form-group align-items-center justify-content-center">
    <%= form.label :set, t('expansion'), class: 'col-3' %>
    <div class="col-6">
      <%= form.select :set, @expansions, class: "ms-2 form-select", selected: @params[:set] %>
    </div>
  </div>

  <div class="row gx-5 mt-3 justify-content-center">
    <% %w[w u b r g c].each do |color| %>
      <%= render partial: 'symbol_checkbox', locals: { form: form, color: color } %>
    <% end %>
  </div>

  <div class="row form-group mt-3 justify-content-center">
    <%= form.label :supertypes, t('supertype'), class: 'col-3' %>
    <div class="col-5">
      <%= form.select :supertypes, @supertypes, class: "ms-1 form-select", selected: @params[:supertypes] %>
    </div>
  </div>

  <div class="row form-group mt-2 justify-content-center">
    <%= form.label :types, t('type'), class: 'col-3' %>
    <div class="col-5">
      <%= form.select :types, @types, class: "ms-1 form-select", selected: @params[:types] %>
    </div>
  </div>

  <div class="row form-group mt-2 justify-content-center">
    <%= form.label :subtypes, t('subtype'), class: 'col-3' %>
    <div class="col-5">
      <%= form.select :subtypes, @subtypes, class: "ms-1 form-select", selected: @params[:subtypes] %>
    </div>
  </div>

  <div class="row form-group mt-2 justify-content-center">
    <%= form.number_field :cost_ge, in: 0..99, class: 'col-1 p-0 ps-1', value: @params[:cost_ge] %>
    <span class="text-dark col-5 pe-0 text-center"><= <%= t('mana-value') %> <=</span>
    <%= form.number_field :cost_le, in: 0..99,  class: 'col-1 p-0 ps-1 ms-1', value: @params[:cost_le]  %>
  </div>

  <div class="row form-group mt-2 justify-content-center">
    <%= form.number_field :power_ge, in: 0..99, class: 'col-1 p-0 ps-1', value: @params[:power_ge] %>
    <span class="text-dark col-5 text-center"><= <%= t('power') %> <=</span>
    <%= form.number_field :power_le, in: 0..99, class: 'col-1 p-0 ps-1 ms-1', value: @params[:power_le]  %>
  </div>

  <div class="row form-group mt-2 justify-content-center">
    <%= form.number_field :toughness_ge, in: 0..99, class: 'col-1 p-0 ps-1', value: @params[:toughness_ge] %>
    <span class="text-dark col-5 pe-0 text-center"><= <%= t('toughness') %> <=</span>
    <%= form.number_field :toughness_le, in: 0..99, class: 'col-1 p-0 ps-1 ms-1', value: @params[:toughness_le]  %>
  </div>

  <div class="row mt-4">
    <div class="col-3"></div>
    <%= form.submit t('search'), class: "btn btn-secondary col-6" %>
    <div class="col-3"></div>
  </div>
<% end %>

app/views/main/_sidebar.html.erb
<% @deck ||= nil %>

<div class="col-4 mt-5 ms-0">
  <div class="menu ps-3 max-height-to-fit position-fixed w-30 overflow-hidden-x">
    <div class="text-center">
      <%= render partial: 'flash', locals: { types: %w[error alert] } %>
    </div>

    <%= render partial: 'menu' %>

    <div id="deck" class="mt-4 row small">
      <%= render partial: 'deck_editor/deck_editor', locals: {deck: @deck} unless @deck.blank? %>
    </div>
  </div>
</div>

app/views/main/add_card.turbo_stream.erb
<%= turbo_stream.update "deck" do %>
  <%= render partial: @deck unless @deck.blank? %>
<% end %>

app/views/main/deck_format.turbo_stream.erb
<%= turbo_stream.update "deck" do %>
  <h4><%= t('new-deck') %></h4>
  <%= form_with url: create_deck_path, method: :post, id: 'deck-create-form', class: 'col-12' do |form| %>

    <div class="form-group row mb-2">
      <%= form.label :deck_name, "#{t('name')}:", class: 'form-label col-4 pe-0 medium-font' %>
      <div class="col-4">
        <%= form.text_field :deck_name, class: 'form-control form-control-sm', required: true %>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label :deck_format, t('choose-format'), class: 'form-label col-4 pe-0 medium-font' %>
      <div class="col-2">
        <%= form.collection_select :deck_format, Format.all, :id, :name, class: 'form-select large-font col-2' %>
      </div>
    </div>

    <div class="">
      <button class="btn btn-primary" id='create-deck-btn'><%= t('create') %></button>
    </div>
  <% end %>

  <script>
      document.getElementById('deck-create-form').addEventListener('submit', () => {
          for (let obj of document.getElementsByClassName('dropdown-btn-container')) {
              obj.classList.add('d-none')
          }

          for (let obj of document.getElementsByClassName('card-buttons')) {
              obj.classList.remove('d-none');
          }
      });
  </script>
<% end %>

app/views/main/index.html.erb
<%= javascript_include_tag "show-extended", defer: "defer" %>

<%= render partial: 'cards', locals: { cards: @cards } %>

<div class="col-1"></div>

<%= render partial: "sidebar" %>

<%= render partial: "footer_pagination", locals: { objects: @cards, buttons: true } %>