config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ru/ do
    root "main#index"

    get 'decks', to: "decks#decks"
    get 'show_deck', to: "decks#show"
    get 'edit_deck', to: "decks#edit"
    post 'copy_deck', to: "decks#copy"
    delete 'delete_deck', to: "decks#delete"

    get 'logout', to: "session#logout"
    get 'login', to: "session#login"
    get 'signup', to: "users#new"

    post 'authorize', to: "session#authorize"

    get 'filtered', to: "main#filtered"
    get 'deck_format', to: "main#deck_format", format: 'turbo_stream'
    patch 'toggle_filters', to: "main#toggle_filters"

    post 'create_deck', to: "deck_editor#create_deck"
    patch 'save_deck', to: "deck_editor#save_deck"
    delete 'delete_current_deck', to: "deck_editor#delete_deck"

    patch 'add_card', to: "deck_editor#add_card"
    patch 'remove_card', to: "deck_editor#remove_card"

    resources :users
  end
end

app/models/user.rb
# frozen_string_literal: true

# user model
class User < ApplicationRecord
  has_secure_password

  validates :name, uniqueness: true, length: { maximum: 20 }

  def self.by_name(str)
    return User.all if str.blank?

    User.where('name like ?', "%#{Card.sanitize_sql_like(str)}%")
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# users controller
class UsersController < ApplicationController
  before_action :redirect_if_not_logged_in, except: %i[create new]
  before_action :set_user, only: %i[show edit update destroy]
  before_action :allow_only_admin, only: %i[edit update destroy]

  layout 'clear', only: [:index]

  # GET /users or /users.json
  def index
    @page = page(User)
    @users = User.by_name(params[:user_name]).page @page
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:current_user_id] = @user.id
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="col-4">
  <%= form_with(model: user) do |form| %>
    <% if user.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name, t('user_name'), style: "display: block", class: "form-label" %>
      <%= form.text_field :name, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= form.label :password, t('password'), style: "display: block", class: "form-label" %>
      <%= form.password_field :password, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :password_confirmation, t('pass_repeat'), class: "form-label", style: "display: block" %>
      <%= form.password_field :password_confirmation, class: "form-control" %>
    </div>

    <% if current_user&.is_admin %>
      <div class="form-group">
        <%= form.label :is_admin, style: "display: block" %>
        <%= form.check_box :is_admin, class: "form-checkbox" %>
      </div>
    <% end %>

    <div class="mt-3">
      <%= form.submit t('submit'), class: "btn btn-outline-primary" %>
    </div>
  <% end %>
</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>" class="row align-items-center mb-3">
  <p class="h5 col-3 ms-2">
<!--    <%#= t('user') %>:-->
    <strong><%= user.name %></strong>
  </p>

  <div class="ms-3 col-1">
    <%= link_to t('decks'), decks_path(user_name: user.name), class: 'btn btn-outline-primary' %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="row">
  <div class="col-8">
    <h1 class="mt-4 row"><%= t('users') %></h1>

    <div id="users mt-3">
      <% @users.each do |user| %>
        <%= render user %>
      <% end %>

      <% if @users.blank? %>
        <p class="h5"><%= t('no-users') %></p>
      <% end %>
    </div>

    <% if current_user&.is_admin %>
      <%= link_to "New user", new_user_path %>
    <% end %>
  </div>

  <div class="col-4 mt-5 ms-0">
    <div class="position-fixed w-25 overflow-visible">
      <%= form_with url: users_path, method: :get do |form| %>
        <div class="form-group row">
          <div class="col-8">
            <%= form.text_field :user_name, class: 'form-control', value: params[:user_name]  %>
          </div>
          <%= form.submit t('search'), class: 'btn btn-outline-primary col-4' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= render partial: "footer_pagination", locals: { objects: @users } %>

app/views/users/new.html.erb
<br>
<br>
<h3 class="mt-5 mb-3"><%= t('sign_up') %></h3>

<%= render "form", user: @user %>

<br>

<% if current_user&.is_admin %>
<div>
  <%= link_to "Back to users", users_path %>
</div>
<% end %>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <% if current_user&.is_admin %>
    <%= link_to "Edit this user", edit_user_path(@user) %>
  <% end %>
  <%= link_to "Back to users", users_path %>

  <% if current_user&.is_admin %>
    <%= button_to "Destroy this user", @user, method: :delete %>
  <% end %>
</div>