config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ru/ do
    root "main#index"

    get 'decks', to: "decks#decks"
    get 'show_deck', to: "decks#show"
    get 'edit_deck', to: "decks#edit"
    post 'copy_deck', to: "decks#copy"
    delete 'delete_deck', to: "decks#delete"

    get 'logout', to: "session#logout"
    get 'login', to: "session#login"
    get 'signup', to: "users#new"

    post 'authorize', to: "session#authorize"

    get 'filtered', to: "main#filtered"
    get 'deck_format', to: "main#deck_format", format: 'turbo_stream'
    patch 'toggle_filters', to: "main#toggle_filters"

    post 'create_deck', to: "deck_editor#create_deck"
    patch 'save_deck', to: "deck_editor#save_deck"
    delete 'delete_current_deck', to: "deck_editor#delete_deck"

    patch 'add_card', to: "deck_editor#add_card"
    patch 'remove_card', to: "deck_editor#remove_card"

    resources :users
  end
end

app/models/deck.rb
# frozen_string_literal: true

# deck model
class Deck < ApplicationRecord
  belongs_to :format
  belongs_to :user

  has_many :cards, class_name: 'CardInDeck', dependent: :delete_all

  validates :name, uniqueness: {
    scope: :user,
    message: 'You already have a deck with such name'
  }

  def add_card(card_instance)
    card_in_deck = cards.find_by(card_instance_id: card_instance.id)
    if card_in_deck.present?
      card_in_deck.num += 1
      card_in_deck.save
    else
      card = CardInDeck.create(deck_id: id, card_instance_id: card_instance.id)
      Deck.refresh_colors(self, card) if card.valid?
      save
    end
  end

  def self.refresh_colors(deck, card_in_deck)
    %w[W U B R G].each do |color|
      if card_in_deck.card_instance.card.manacost&.include?(color) && deck.colors.exclude?(color)
        deck.colors += "{#{color}}"
      end
    end

    deck.save
  end

  def self.remove_colors(deck, card_in_deck)
    %w[W U B R G].each do |color|
      next unless card_in_deck.card_instance.card.manacost&.include?(color)

      deck.colors.gsub!("{#{color}}", '') unless deck.color_without?(card_in_deck, color)
    end

    deck.save
  end

  def self.by_user(name)
    if name.blank?
      Deck.order(:user_id)
    else
      Deck.joins(:user).where('users.name = ?', name)
    end
  end

  def self.copy(deck, user = nil)
    user_id = user.blank? ? deck.user_id : user.id

    copied = Deck.create(name: deck.get_copied_name(user_id), format_id: deck.format_id,
                         user_id:, colors: deck.colors)

    deck.cards.each do |card|
      CardInDeck.create(deck_id: copied.id, card_instance_id: card.card_instance_id, num: card.num)
    end

    copied
  end

  def color_without?(card_in_deck, color)
    contains = false

    cards.filter { |card| card != card_in_deck }.each do |card|
      contains = card.card_instance.card.manacost&.include? color
      break if contains
    end

    contains
  end

  def get_copied_name(user_id)
    count = Deck.where('name like :deck_name and user_id = :user_id',
                       user_id:,
                       deck_name: "%#{Deck.sanitize_sql_like(name)} #{I18n.t('copied')}%").count
    "#{name} #{I18n.t('copied')} #{count unless count.zero?}".chomp ' '
  end

  private

  def validate_card_instance_num
    if cards.any? { |card| card.card_instance.card.supertypes.exclude?('Basic') && card.total > format.max_same }
      errors.add(:cards, "Can't have more then #{format.max_same} same cards")
    end
  end
end

app/controllers/decks_controller.rb
# frozen_string_literal: true

# decks controller
class DecksController < ApplicationController
  before_action :init_deck, only: [:edit]
  before_action :redirect_if_no_deck, except: [:decks]
  before_action :redirect_if_not_logged_in, except: %i[decks show]

  layout 'clear', only: [:decks]

  def decks
    @page = page(Deck)
    @decks = Deck.by_user(params[:user_name]).page @page
  end

  def show
    @deck = Deck.find_by(id: params[:deck_id])
    redirect_to root_path if @deck.blank?
  end

  def copy
    original = Deck.find_by(id: params[:deck_id])
    copy = Deck.copy(original, current_user)
    redirect_to show_deck_path(deck_id: copy.id)
  end

  def delete
    @deck = Deck.find_by(id: params[:deck_id])
    @deck&.destroy
    redirect_to decks_path(user_id: current_user&.id)
  end

  def edit
    @deck&.save

    session[:is_deckbuilding] = true
    session[:deck_id] = params[:deck_id]

    redirect_to root_path
  end

  private

  def redirect_if_no_deck
    redirect_back(fallback_location: decks_path) if params[:deck_id].blank?
  end
end

app/views/decks/_deck.html.erb
<div class="row align-items-center mt-5">
  <p class="col-2 h4 bold"><%= deck.name %></p>
  <p class="col-2 h6"><%= t('format') %>: <%= deck.format.name %></p>
</div>

<div class="row mt-2">
  <% if current_user&.id == deck.user.id %>
    <%= link_to t('edit'), edit_deck_path(deck_id: deck.id), class: 'btn btn-outline-primary col-1 ms-2' %>
  <% end %>

  <% if current_user.present? %>
    <%= link_to t('copy'), copy_deck_path(deck_id: deck.id), class: 'btn btn-outline-primary col-1 ms-2', data: {turbo_method: :post} %>
  <% end %>

  <% if current_user&.id == deck.user.id %>
    <%= link_to t('delete'), delete_deck_path(deck_id: deck.id), class: "col-1 btn btn-outline-danger ms-2", id: "delete-deck-btn",
                data: {turbo_method: :delete, turbo_confirm: t('sure?')} %>
  <% end %>
</div>

<div class="col-6 ms-3 mb-3">
  <% Card.all_types.each do |type| %>
    <% cards = deck.cards.all %>
    <% filtered = cards.filter { |card| card.card_instance.card.types.include? type }.sort_by { |card| card.card_instance.card.mana_value } %>

    <% unless filtered.empty? %>
      <h6 class="mt-3 bold"><%= t(type.downcase) %></h6>
      <div class="ms-2"></div>
      <%= render partial: 'deck_editor/deck_header' %>
      <div class="cards">
        <% filtered.each do |card| %>
          <%= render partial: 'card_in_decks/card_in_deck_view', locals: { card: card } %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

<script>
    for (let card of document.getElementsByClassName('deck-card')) {
        let img = card.getElementsByClassName('deck-card-img')[0];

        card.addEventListener('mouseenter', () => {
            img.classList.remove('d-none')
        });

        card.addEventListener('mouseleave', () => {
            img.classList.add('d-none')
        });
    }
</script>

app/views/decks/_deck_editor.html.erb
<%= form_with url: save_deck_path, class: 'align-items-center mt-2', method: :patch, id: 'deck-save-form' do |form| %>
  <h4 class="bold">New Deck</h4>

  <%= render partial: 'flash', locals: { types: ['deck_alert'] } %>

  <div class="row align-items-center">
    <%= form.label :deck_name, 'Name', class: 'col-2 h5' %>
    <div class="col-5">
      <%= form.text_field :deck_name, class: 'form-control', required: true, value: deck.name %>
    </div>

    <div class="col-5">
      <%= form.collection_select :deck_format, Format.all, :id, :name, selected: deck.format.id, class: 'form-select large-font ms-3 p-2' %>
    </div>
  </div>

  <% %w[Creature Enchantment Planeswalker Sorcery Instant Artifact Land].each do |type| %>
    <% cards = deck.cards.all %>
    <% filtered = cards.filter { |card| card.card_instance.card.types.include? type }.sort_by { |card| card.card_instance.card.mana_value } %>

    <% unless filtered.empty? %>
      <h6 class="mt-3 bold"><%= type.pluralize(2) %></h6>
      <%= render partial: 'decks/deck_header' %>
      <div class="cards">
        <% filtered.each do |card| %>
          <%= render card %>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <div class="row mt-3 justify-content-center">
    <%= form.submit 'Save', class: "col-3 btn btn-outline-success" %>
    <%= link_to 'Delete', delete_deck_path, class: "col-3 btn btn-outline-danger ms-2", id: "delete-deck-btn",
                data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
  </div>
<% end %>

<script>
    function abort_deck_building() {
        for (let obj of document.getElementsByClassName('card-buttons')) {
            obj.classList.add('d-none');
        }

        for (let obj of document.getElementsByClassName('dropdown-btn-container')) {
            obj.classList.remove('d-none')
        }

        document.getElementById('new-deck-btn').classList.remove('d-none')
    }

  document.getElementById('delete-deck-btn').addEventListener('click', abort_deck_building);
  document.getElementById('deck-save-form').addEventListener('submit', abort_deck_building);

  for (let card of document.getElementsByClassName('deck-card')) {
      let img = card.getElementsByClassName('deck-card-img')[0];
      let info = card.getElementsByClassName('deck-card-info')[0];

      info.addEventListener('mouseenter', () => {
          img.classList.add('shown')
      });

      info.addEventListener('mouseleave', () => {
          img.classList.remove('shown')
      });
  }
</script>

app/views/decks/_deck_entry.html.erb
<div class="row mt-1 card-entry small align-items-center">
  <div id="<%= dom_id deck %>" class="entry-base row col-6 ms-1 list-group list-group-horizontal p-0 outline">
    <div class="col-4 list-group-item centered">
      <span class="bold"><%= deck.name %></span>
    </div>
    <div class="col-3 list-group-item centered">
      <span><%= deck.user.name %></span>
    </div>
    <div class="col-2 list-group-item centered">
      <span><%= replace_mtg_symbols(deck.colors) %></span>
    </div>
    <div class="col-3 list-group-item centered">
      <span><%= deck.format.name %></span>
    </div>
  </div>

  <div class="col-1 ms-4">
    <div class="row">
      <%= link_to t('view'), show_deck_path(deck_id: deck.id), class: 'btn btn-outline-primary view-btn' %>
    </div>
  </div>
</div>

app/views/decks/decks.html.erb
<% if @decks.present? %>
  <div class="row">
    <div class="row mt-5">
      <div class="list-group row col-6 list-group-horizontal outline ms-1 pe-0">
        <div class="col-4 list-group-item centered">
          <span><%= t('name') %></span>
        </div>
        <div class="col-3 list-group-item centered">
          <span><%= t('author') %></span>
        </div>
        <div class="col-2 list-group-item centered">
          <span><%= t('colors') %></span>
        </div>
        <div class="col-3 list-group-item centered">
          <span><%= t('format') %></span>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="row mt-5">
    <div class="h4 col-4">
      <%= t('no-decks') %>
    </div>
    <%= link_to t('back'), 'javascript:history.back()', class: 'btn btn-outline-primary col-1' %>
  </div>
<% end %>

<div id="decks" class="row mb-3">
  <% @decks.each do |deck| %>
    <%= render partial: 'decks/deck_entry', locals: { deck: deck } %>
  <% end %>
</div>

<%= render partial: "footer_pagination", locals: { objects: @decks } %>

app/views/decks/delete_deck.turbo_stream.erb
<%= turbo_stream.update "deck" do %><% end %>

app/views/decks/show.html.erb
<%= render @deck %>