config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ru/ do
    root "main#index"

    get 'decks', to: "decks#decks"
    get 'show_deck', to: "decks#show"
    get 'edit_deck', to: "decks#edit"
    post 'copy_deck', to: "decks#copy"
    delete 'delete_deck', to: "decks#delete"

    get 'logout', to: "session#logout"
    get 'login', to: "session#login"
    get 'signup', to: "users#new"

    post 'authorize', to: "session#authorize"

    get 'filtered', to: "main#filtered"
    get 'deck_format', to: "main#deck_format", format: 'turbo_stream'
    patch 'toggle_filters', to: "main#toggle_filters"

    post 'create_deck', to: "deck_editor#create_deck"
    patch 'save_deck', to: "deck_editor#save_deck"
    delete 'delete_current_deck', to: "deck_editor#delete_deck"

    patch 'add_card', to: "deck_editor#add_card"
    patch 'remove_card', to: "deck_editor#remove_card"

    resources :users
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# base controller
class ApplicationController < ActionController::Base
  around_action :switch_locale

  def default_url_options
    { locale: I18n.locale }
  end

  def user_authenticated
    return false if session[:current_user_id].nil?

    true
  end

  def current_user
    return nil unless user_authenticated

    @current_user ||= User.find_by_id(session[:current_user_id])
  end

  def allow_only_admin
    redirect_back(fallback_location: root_path) unless current_user&.is_admin
  end

  helper_method :current_user, :user_authenticated

  protected

  def redirect_if_not_logged_in
    redirect_to login_path unless current_user.present?
  end

  def init_deck
    return @deck = nil if session[:deck_id].blank?

    @deck ||= Deck.find_by_id(session[:deck_id])
  end

  def page(type)
    page = params[:page].present? ? params[:page] : 1
    [type.page.total_pages, page.to_i].min
  end

  private

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def process_text(str, size=MTG_SYMBOL_SIZE)
    return if str.nil?
    replace_mtg_symbols(str.strip.gsub(/\n/, '<br/>'), size).html_safe
  end

  MTG_SYMBOL_SIZE_BIG = '24x24'
  MTG_SYMBOL_SIZE_MID = '20x20'
  MTG_SYMBOL_SIZE = '18x18'
  MTG_SYMBOL_SIZE_MIN = '14x14'

  def replace_mtg_symbols(str, size=MTG_SYMBOL_SIZE)
    return if str.nil?

    str.gsub(Card::MTG_SYMBOL) do |match|
      image_tag("symbols/#{match[1...-1].delete('/').downcase}.svg", size: size)
    end.html_safe
  end

  def get_mtg_symbols(str)
    str.scan(Card::MTG_SYMBOL).map { |match| "symbols/#{match.first[1...-1].delete('/').downcase}.svg" }
  end

  def checked?(key)
    @params[key].present? ? !@params[key].to_i.zero? : false
  end

  def add_locale(locale)
    url_for(params.clone.permit!.merge(locale: locale, only_path: true))
  end
end

app/views/application/_flash.html.erb
<div class="flash">
  <% flash.each do |type, msg| %>
    <% if types.include? type %>
      <p class="text-danger"><%= msg %></p>
    <% end %>
  <% end %>
</div>

app/views/application/_footer_default.html.erb
<footer class="footer fixed-bottom bg-dark row mt-3 d-flex align-items-center justify-content-end">
  <div class="col-1">
    <%= link_to("EN", add_locale('en'), class: 'btn btn-outline-primary text-light me-1') %>
    <%= link_to("RU", add_locale('ru'), class: 'btn btn-outline-primary text-light') %>
  </div>
</footer>

app/views/application/_footer_pagination.html.erb
<% buttons ||= false %>

<footer class="footer fixed-bottom bg-dark row mt-3 d-flex align-items-center">
  <div class="col-8 ms-5">
    <%= paginate objects %>
  </div>
  <% if buttons %>
    <div class="col-2 d-flex align-items-center">
      <%= button_to t('new-deck'), deck_format_path, id: 'new-deck-btn', class: "#{'d-none' if !user_authenticated || user_is_deckbuilding}
          btn btn-outline-secondary text-light", method: :get, form: {"data-type": "turbo_stream" }%>
    </div>
  <% end %>
  <div class="col-1">
    <%= link_to("EN", add_locale('en'), class: 'btn btn-outline-primary text-light me-1') %>
    <%= link_to("RU", add_locale('ru'), class: 'btn btn-outline-primary text-light') %>
  </div>
</footer>

app/views/application/_layout.html.erb
<% footer ||= nil %>

<!DOCTYPE html>
<html>
<head>
  <title>MtG</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "styles", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag t('http_cdn_jsdelivr_net_npm_keyrune_latest_css_keyru') %>

  <%= javascript_importmap_tags %>
</head>

<body class="container-fluid pe-0 w-100">
<header class="navbar navbar-expand-md navbar-dark fixed-top bg-dark row">
  <h1 class="col-5 ms-3 mt-3 text-light"><%= link_to 'MtG Cardbase', root_path %></h1>
  <div class="col-4 d-flex align-items-center justify-content-center">
    <% if current_user.present? %>
      <%= link_to t('users'), users_path, class: "text-light h5 me-3 btn btn-outline-secondary menu-btn"%>
      <%= link_to "#{t('your')} #{t('decks')}", decks_path(user_name: current_user&.name), class: "text-light h5 me-3 btn btn-outline-secondary menu-btn"%>
    <% end %>

    <%= link_to t('decks'), decks_path, class: "text-light h5 me-3 btn btn-outline-secondary menu-btn"%>
    <%= link_to t('cards'), root_path, class: "text-light h5 me-3 btn btn-outline-secondary menu-btn"%>
  </div>
  <div class="col-3 d-flex align-items-center justify-content-center">
    <% if current_user.present? %>
      <p class="h5 text-light"><%= t('hello') %>, <%= current_user.name %>!</p>
      <%= link_to t('sign_out'), logout_path, class: "text-light h5 ms-3 btn btn-outline-secondary menu-btn"%>
    <% else %>
      <%= link_to t('log_in'), login_path, class: "text-light h5 me-3 btn btn-outline-secondary menu-btn"%>
      <%= link_to t('sign_up'), signup_path, class: "text-light h5 btn btn-outline-secondary menu-btn"%>
    <% end %>
  </div>
</header>

<main class="row gx-0">
  <%= yield %>
</main>

<%= render partial: footer unless footer.blank? %>
</body>
</html>

app/views/application/_manacost.html.erb
<% if card.manacost.nil? %>
  -
<%  else  %>
  <% get_mtg_symbols(card.manacost).each do |img| %>
    <%=  image_tag(img, size: size)  %>
  <% end %>
<% end %>

app/views/application/_set_symbol.html.erb
<% size ||= 2 %>
<i class="<%= card.expansion_symbol(size) %>"></i>

app/views/application/_symbol_checkbox.html.erb
<div class="col-1 form-check form-check-secondary me-4">
  <% color_sym = "color_#{color}".to_sym  %>
  <%= form.check_box color_sym, class: "form-check-input color-secondary me-0", checked: checked?(color_sym) %>
  <%= form.label color_sym, image_tag("symbols/#{color}.svg", size: ApplicationHelper::MTG_SYMBOL_SIZE_MID), class: 'symbol-btn form-check-label' %>
</div>